import fs from 'fs';

const packageJson = JSON.parse(fs.readFileSync('./package.json', 'utf8'));
const outputPath = './src/wasm-from-cdn.ts';

const packageName = packageJson.name;
const version = packageJson.version;
const compatPackage = packageJson.wllama64.compatPackage;
const compatVersion = packageJson.wllama64.compatVersion;
const outputContent = `
// This file is generated by scripts/generate_wasm_from_cdn.js
// Do not edit this file directly

const WasmFromCDN = {
  default: 'https://cdn.jsdelivr.net/npm/${packageName}@${version}/esm/wasm/wllama.wasm',
};

export const WasmCompatFromCDN = {
  worker: 'https://cdn.jsdelivr.net/npm/${compatPackage}@${compatVersion}/wasm/wllama.js',
  wasm: 'https://cdn.jsdelivr.net/npm/${compatPackage}@${compatVersion}/wasm/wllama.wasm',
};

export default WasmFromCDN;
`.trim();

fs.writeFileSync(outputPath, outputContent);
