// This file is generated by scripts/generate_wasm_from_cdn.js
// Do not edit this file directly

const WasmFromCDN = {
  default: 'https://cdn.jsdelivr.net/npm/wllama64@1.0.0-rc.1/esm/wasm/wllama.wasm',
};

export const WasmCompatFromCDN = {
  worker: 'https://cdn.jsdelivr.net/npm/@wllama/wllama-compat@3.6.0/wasm/wllama.js',
  wasm: 'https://cdn.jsdelivr.net/npm/@wllama/wllama-compat@3.6.0/wasm/wllama.wasm',
};

export default WasmFromCDN;